package android.support.constraint.p026a;

import java.util.ArrayList;

public final class C0185f {
    public long f695A;
    public long f696B;
    public ArrayList<String> f697C;
    public long f698D;
    public long f699a;
    public long f700b;
    public long f701c;
    public long f702d;
    public long f703e;
    public long f704f;
    public long f705g;
    public long f706h;
    public long f707i;
    public long f708j;
    public long f709k;
    public long f710l;
    public long f711m;
    public long f712n;
    public long f713o;
    public long f714p;
    public long f715q;
    public long f716r;
    public long f717s;
    public long f718t;
    public long f719u;
    public long f720v;
    public long f721w;
    public long f722x;
    public long f723y;
    public long f724z;

    public final String toString() {
        StringBuilder stringBuilder = new StringBuilder("\n*** Metrics ***\nmeasures: ");
        stringBuilder.append(this.f699a);
        stringBuilder.append("\nadditionalMeasures: ");
        stringBuilder.append(this.f700b);
        stringBuilder.append("\nresolutions passes: ");
        stringBuilder.append(this.f701c);
        stringBuilder.append("\ntable increases: ");
        stringBuilder.append(this.f702d);
        stringBuilder.append("\nmaxTableSize: ");
        stringBuilder.append(this.f714p);
        stringBuilder.append("\nmaxVariables: ");
        stringBuilder.append(this.f719u);
        stringBuilder.append("\nmaxRows: ");
        stringBuilder.append(this.f720v);
        stringBuilder.append("\n\nminimize: ");
        stringBuilder.append(this.f703e);
        stringBuilder.append("\nminimizeGoal: ");
        stringBuilder.append(this.f718t);
        stringBuilder.append("\nconstraints: ");
        stringBuilder.append(this.f704f);
        stringBuilder.append("\nsimpleconstraints: ");
        stringBuilder.append(this.f705g);
        stringBuilder.append("\noptimize: ");
        stringBuilder.append(this.f706h);
        stringBuilder.append("\niterations: ");
        stringBuilder.append(this.f707i);
        stringBuilder.append("\npivots: ");
        stringBuilder.append(this.f708j);
        stringBuilder.append("\nbfs: ");
        stringBuilder.append(this.f709k);
        stringBuilder.append("\nvariables: ");
        stringBuilder.append(this.f710l);
        stringBuilder.append("\nerrors: ");
        stringBuilder.append(this.f711m);
        stringBuilder.append("\nslackvariables: ");
        stringBuilder.append(this.f712n);
        stringBuilder.append("\nextravariables: ");
        stringBuilder.append(this.f713o);
        stringBuilder.append("\nfullySolved: ");
        stringBuilder.append(this.f715q);
        stringBuilder.append("\ngraphOptimizer: ");
        stringBuilder.append(this.f716r);
        stringBuilder.append("\nresolvedWidgets: ");
        stringBuilder.append(this.f717s);
        stringBuilder.append("\noldresolvedWidgets: ");
        stringBuilder.append(this.f695A);
        stringBuilder.append("\nnonresolvedWidgets: ");
        stringBuilder.append(this.f696B);
        stringBuilder.append("\ncenterConnectionResolved: ");
        stringBuilder.append(this.f721w);
        stringBuilder.append("\nmatchConnectionResolved: ");
        stringBuilder.append(this.f722x);
        stringBuilder.append("\nchainConnectionResolved: ");
        stringBuilder.append(this.f723y);
        stringBuilder.append("\nbarrierConnectionResolved: ");
        stringBuilder.append(this.f724z);
        stringBuilder.append("\nproblematicsLayouts: ");
        stringBuilder.append(this.f697C);
        stringBuilder.append("\n");
        return stringBuilder.toString();
    }
}
